services:
  pekka-app:
    build: .
    container_name: pekka-app
    ports:
      - "5008:5005"
    environment:
      - PEKKA_PIN=${PEKKA_PIN}
      - SECRET_KEY=${SECRET_KEY}
      - GLUETUN_URL=http://192.168.1.173:8001


    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5005/login')"]
      interval: 30s
      timeout: 10s
      retries: 3
